/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Woody' at '17-7-26 下午5:20' with Gradle 3.1
 *
 * @author Woody, @date 17-7-26 下午5:20
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
